### PR TITLE
added workaround for aufs in debian

### PR DESCRIPTION
**Pull request by egandro**

### CODE REVIEW

**Comment by JonasProgrammer** [comment]
LGTM, but untested.

@mxschmitt  Thoughts on this?

**Comment by mxschmitt** [comment]
LGTM, for users who want to use `aufs`. (But in general `overlay2` should be [the best](https://sthbrx.github.io/blog/2015/10/30/docker-just-stop-using-aufs/), afaik.)

**Comment by egandro** [comment]
> LGTM, for users who want to use `aufs`. (But in general `overlay2` should be [the best](https://sthbrx.github.io/blog/2015/10/30/docker-just-stop-using-aufs/), afaik.)

Yes sorry - aufs <-> overlayfs2 recomendaton just changed a few weeks ago.

**Comment by egandro** [comment]
So in general the overlay2 hint is afaik no longer needed.

-> https://docs.docker.com/v17.09/engine/userguide/storagedriver/selectadriver/#supported-storage-drivers-per-linux-distribution

**Comment by JonasProgrammer** [comment]
While I'm not entirely positive it is still required nowadays, explicitly stating `overlay2` was definitely required in early 2018 (when 17.09 was likely released already), at least with certain Debian (Stretch) images and certain `docker-machine` versions.

The way I see it, we should generally add a disclaimer to let docker decided in the first place and only use the explicit `overlayfs2` option, if something goes wrong. As for the `aufs` option, perhaps we can add a notice that this workaround exists for compatibility reasons, but is generally not recommended for newly set up environments?

**Comment by JonasProgrammer** [comment]
@egandro @mxschmitt Could you please check my changes? I've attempted to state more clearly what the recommended way is nowadays and restructure the README in a way, so we have a fixed place for known problems like this.

**Comment by egandro** [comment]
OK with your Readme Version here. 

I suggest adding the link to the docker documentation to that - or at last give some reference to RTFM on this.  I wasn't aware of this rapid changement :)

**Comment by egandro** [comment]
I always double check.

I am having now (Thu Nov 15 16:29:10 CET 2018) issues without the "--engine-storage-driver overlay2" flag.

Damn...

**Comment by egandro** [comment]
This is fishy :( Currently please use your "--engine-storage-driver overlay2" - this worked a few days ago (maybe there was a docker.ce minor change or some folks at debian decided what 'stable' is).

I sugged adding the hint to aufs - in case anybody needs it.

Sorry for generating trouble here :( As so often - i had best intensions in mind by "solving" a problem.

**Comment by mxschmitt** [comment]
Closing and referring to the latest Docker docs: https://docs.docker.com/storage/storagedriver/select-storage-driver/

**Pull request closed without merging**
